/********** PLANTS ACTION TYPES *************** */

export const FETCH_PLANETS_STARTED = "FETCH_PLANETS_STARTED";
export const FETCH_PLANETS_END = "FETCH_PLANETS_END";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";

export const FETCH_MOVIES_STARTED = "FETCH_MOVIES_STARTED";
export const FETCH_MOVIES_END = "FETCH_MOVIES_END";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
